- name: frontend playbook
  hosts: all
  become: true
  tasks:
    - name: set-prompt
      ansible.builtin.sheel: set-prompt frontend

    - name: installing nginx package
      ansible.builtin.dnf:
        name: nginx
        state: present