
- name: installing nginx package
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: import app-prereq
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: start a systemctl service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true